services:
  db:
    image: postgres
    container_name: esp_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: esp_data
    ports:
      - "5432:5432"
    networks:
      - lan_network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: /home/ec2-user/temp-monitor/backend
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - lan_network
    env_file:
      - ./backend/.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/esp_data
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  frontend:
    build: /home/ec2-user/temp-monitor/frontend
    container_name: frontend
    networks:
      - lan_network
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ec2-user/ssl/certs:/etc/ssl/certs:ro
      - /home/ec2-user/ssl/private:/etc/ssl/private:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    networks:
      - lan_network
    depends_on:
      - frontend
      - backend

volumes:
  postgres-data:

networks:
  lan_network:
    driver: bridge
