services:
  db:
    image: postgres
    container_name: esp_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: esp_data
    ports:
      - "5432:5432"
    networks:
      - lan_network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - lan_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/esp_data
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  frontend:
    build: ../frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - lan_network
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl/certs:/etc/ssl/certs:ro
      - ./ssl/private:/etc/ssl/private:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  postgres-data:

networks:
  lan_network:
    driver: bridge